export function renderHelp() {
  return [
    'Ubertooth Windows Host CLI',
    '',
    'Safe / guarded commands:',
    '  help            Show this help text',
    '  detect          Detect Ubertooth devices on this Windows host',
    '  info            Print raw discovery info as JSON',
    '  version         Print a concise firmware/API/build summary',
    '  reset           Send a guarded reboot request (requires --yes)',
    '  flash           Run the official guarded firmware flow (requires --file and --yes)',
    '  capture         Run the raw live BLE inspector MVP (upstream follow-mode inspired)',
    '  probe           Print driver/class/readiness metadata',
    '  transport       Prove safe read-only WinUSB open + USB descriptor reads',
    '  protocol        Read official version/info protocol fields',
    '  runtime         Read official getter-only runtime state',
    '  status          Print a single human-friendly summary of the safe capabilities',
    '  specan          Run spectrum analyzer (requires ubertooth-specan.exe)',
    '  rx              Run Classic Bluetooth discovery (requires ubertooth-rx.exe)',
    '  dump            Run raw bit stream dump (requires ubertooth-dump.exe)',
    '  afh             Run AFH channel map detection (requires ubertooth-afh.exe)',
    '  util            Run device utility (requires ubertooth-util.exe)',
    '  btle            Run BLE analysis (sniffing, following, interference)',
    '  duty-cycle      Show transmission usage and safety limits',
    '  scan            Run Bluetooth device scan (Hardware-bridged via Windows APIs)',
    '  follow          Run Bluetooth connection follow (Hardware-bridged via Windows APIs)',
    '  ducky           Run Uberducky/Rubber Ducky emulation (TX - Requires confirmation)',
    '  tx              Run raw symbol transmission (TX - Requires confirmation)',
    '  debug           Read/Write radio registers (requires ubertooth-debug.exe)',
    '  ego             Run Ubertooth Ego mode (requires ubertooth-ego.exe)',
    '  repair          Run automated driver/binding repair (requires admin)',
    '  analyze         Summarize BLE packet logs from a file (requires --file)',
    '',
    'Flags:',
    '  --json          Emit JSON for the selected command',
    '  --yes           Required for reset/flash/repair because they intentionally change device state',
    '  --full          Used with repair for deep driver recovery (remove + rescan)',
    '  --file, -f, -w  Path to the official .dfu image used by flash or output for dump',
    '  --tool          Optional path to ubertooth-btle(.exe) if it is not on PATH',
    '  --channel, -c   Optional advertising channel for capture/ducky (0-78)',
    '  --device, -U    Optional device index for multi-Ubertooth setups',
    '  --rssi          Optional RSSI output for capture',
    '  --follow, -f    Optional connection follow mode for capture/btle',
    '  --no-follow, -n Do not follow connections (btle)',
    '  --promisc, -p   Promiscuous sniffing (btle)',
    '  --interfere, -i Interference/Jamming (btle)',
    '  --interfere-continuous, -I Continuous interference (btle)',
    '  --target, -t    Required target ID/address for follow command',
    '  --address, -a   Access Address (btle)',
    '  --slave, -s     Faux slave mode (btle)',
    '  --pcapng, -r    Output to PCAPNG file (btle)',
    '  --pcap, -q      Output to PCAP file (btle)',
    '  --pcap-ppi, -c  Output to PCAP with PPI (btle)',
    '  --verify-crc, -v Verify CRC (btle)',
    '  --aa-offenses, -x Access Address offenses limit (btle)',
    '  --quack, -q     Optional UUID for ducky command',
    '  --lap, -l       Optional LAP for follow/tx commands',
    '  --uap, -u       Optional UAP for follow/tx commands',
    '  --bdaddr, -a    Optional BD ADDR for ducky command',
    '  --register, -r  Optional register index for debug command',
    '  --verbose, -v   Optional verbose output for debug command',
    '  --timeout-seconds  Optional bounded runtime for live capture or scan',
    '  --output, -o    Optional file path to save raw capture or specan output',
    '  --i-confirm-antenna-is-attached',
    '                  Required for transmission commands (ducky, tx, btle -s) to protect hardware.',
    '',
    'Windows setup helper:',
    '  npm run setup-flash-tools',
    '                  Stage the validated repo-local official DFU tools and firmware paths',
    '                  without installing drivers, modifying PATH, or downloading/building dependencies.',
    '',
    'Safety boundary:',
    '  - Getter/info commands stay control-IN only',
    '  - reset is a guarded reboot request only',
    '  - flash uses the official ubertooth-dfu flow only',
    '  - No undocumented DFU/write path',
    '  - No write-path chaining with reset',
    '',
    'Examples:',
    '  npm run status',
    '  npm run version',
    '  npm run capture -- --channel 37 --timeout-seconds 10',
    '  npm run capture -- --channel 37 --timeout-seconds 10 --output capture.txt',
    '  npm run setup-flash-tools',
    '  npm run reset -- --yes',
    '  npm run flash -- --file .\\firmware\\bluetooth_rxtx.dfu --yes'
  ].join('\n');
}
