export function renderHelp() {
  return [
    'Ubertooth Windows Host CLI',
    '',
    'Safe / guarded commands:',
    '  help            Show this help text',
    '  detect          Detect Ubertooth devices on this Windows host',
    '  info            Print raw discovery info as JSON',
    '  version         Print a concise firmware/API/build summary',
    '  reset           Send a guarded reboot request (requires --yes)',
    '  flash           Run the official guarded firmware flow (requires --file and --yes)',
    '  capture         Run the raw live BLE inspector MVP (upstream follow-mode inspired)',
    '  probe           Print driver/class/readiness metadata',
    '  transport       Prove safe read-only WinUSB open + USB descriptor reads',
    '  protocol        Read official version/info protocol fields',
    '  runtime         Read official getter-only runtime state',
    '  status          Print a single human-friendly summary of the safe capabilities',
    '',
    'Flags:',
    '  --json          Emit JSON for the selected command',
    '  --yes           Required for reset/flash because they intentionally change device state',
    '  --file          Path to the official .dfu image used by flash',
    '  --tool          Optional path to ubertooth-dfu(.exe) if it is not on PATH',
    '  --channel       Optional advertising channel for capture (37, 38, or 39)',
    '  --timeout-seconds  Optional bounded runtime for live capture verification',
    '',
    'Windows setup helper:',
    '  npm run setup-flash-tools',
    '                  Stage the validated repo-local official DFU tools and firmware paths',
    '                  without installing drivers, modifying PATH, or downloading/building dependencies.',
    '',
    'Safety boundary:',
    '  - Getter/info commands stay control-IN only',
    '  - reset is a guarded reboot request only',
    '  - flash uses the official ubertooth-dfu flow only',
    '  - No undocumented DFU/write path',
    '  - No write-path chaining with reset',
    '',
    'Examples:',
    '  npm run status',
    '  npm run version',
    '  npm run capture -- --channel 37 --timeout-seconds 10',
    '  npm run setup-flash-tools',
    '  npm run reset -- --yes',
    '  npm run flash -- --file .\\firmware\\bluetooth_rxtx.dfu --yes'
  ].join('\n');
}
