name: ci

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c48363413237129d49f600394734039263356 # v4.3.1

      - name: Setup Node
        uses: actions/setup-node@53b8394e545a775178f52524783378180af0d1f8 # v4.3.0
        with:
          node-version: 22
          cache: npm

      - name: Show versions
        run: |
          node --version
          npm --version

      - name: Run checks
        run: npm run check
